import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Header from '../components/Header'
import TopRes from '../components/TopRes'
import Popular from '../components/Popular'
import Chefs from '../components/Chef'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <main className="font-lora font-extrabold">
    <Navbar/>
    <Header/>
    <TopRes/>
    <Popular/>
    <Chefs/>
  </main>
    </div>
  )
}
